export const fonts = [
  'Poppins',
  'Dancing Script',
  'Pacifico',
  'Roboto',
  'Great Vibes',
  'Lobster',
  'Playfair Display',
  'Sacramento',
  'Courgette',
  'Caveat',
  'Amatic SC',
  'Indie Flower',
  'Shadows Into Light',
  'Satisfy',
  'Tangerine',
  'Merriweather',
  'Cinzel Decorative',
  'Parisienne',
  'Cookie',
  'Kaushan Script',
  'Montserrat',
  'Raleway',
  'Quicksand',
  'Noto Serif',
  'Josefin Sans',
]
